GET http://localhost:5100/api/accounts/7a13aa13-3299-449c-ba3e-8bfa0468c3ce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZWxpbUBzZWxpbS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImp0aSI6ImNmYTkzNmRiLWQxYTYtNDJmNC04ZTIzLTZiNmE5YzU1NDViYSIsImV4cCI6MTczNDA3MzE3NSwiaXNzIjoiSnd0QXV0aEFwcCIsImF1ZCI6Ikp3dEF1dGhBcHBVc2VyIn0.FDKjUwilCkGU1W2JSYMjp0HMjtmfmHV3vqqIfFWhD9o
Content-Type: application/json


### 
GET  http://localhost:5100/api/accounts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZWxpbUBzZWxpbS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImp0aSI6ImNmYTkzNmRiLWQxYTYtNDJmNC04ZTIzLTZiNmE5YzU1NDViYSIsImV4cCI6MTczNDA3MzE3NSwiaXNzIjoiSnd0QXV0aEFwcCIsImF1ZCI6Ikp3dEF1dGhBcHBVc2VyIn0.FDKjUwilCkGU1W2JSYMjp0HMjtmfmHV3vqqIfFWhD9o
Content-Type: application/json

### 
DELETE  http://localhost:5100/api/accounts/7a13aa13-3299-449c-ba3e-8bfa0468c3ce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZWxpbUBzZWxpbS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImp0aSI6ImNmYTkzNmRiLWQxYTYtNDJmNC04ZTIzLTZiNmE5YzU1NDViYSIsImV4cCI6MTczNDA3MzE3NSwiaXNzIjoiSnd0QXV0aEFwcCIsImF1ZCI6Ikp3dEF1dGhBcHBVc2VyIn0.FDKjUwilCkGU1W2JSYMjp0HMjtmfmHV3vqqIfFWhD9o
Content-Type: application/json


### 
PATCH  http://localhost:5100/api/accounts/52c53b06-c55d-437a-941e-008c0921c23d/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZWxpbUBzZWxpbS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImp0aSI6ImNmYTkzNmRiLWQxYTYtNDJmNC04ZTIzLTZiNmE5YzU1NDViYSIsImV4cCI6MTczNDA3MzE3NSwiaXNzIjoiSnd0QXV0aEFwcCIsImF1ZCI6Ikp3dEF1dGhBcHBVc2VyIn0.FDKjUwilCkGU1W2JSYMjp0HMjtmfmHV3vqqIfFWhD9o
Content-Type: application/json

{
  "Balance": 1000
}

### 
PATCH  http://localhost:5100/api/accounts/52c53b06-c55d-437a-941e-008c0921c23d/subtractBalance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZWxpbUBzZWxpbS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImp0aSI6ImNmYTkzNmRiLWQxYTYtNDJmNC04ZTIzLTZiNmE5YzU1NDViYSIsImV4cCI6MTczNDA3MzE3NSwiaXNzIjoiSnd0QXV0aEFwcCIsImF1ZCI6Ikp3dEF1dGhBcHBVc2VyIn0.FDKjUwilCkGU1W2JSYMjp0HMjtmfmHV3vqqIfFWhD9o
Content-Type: application/json

{
  "Balance": 777
}


### 
PATCH  http://localhost:5100/api/accounts/52c53b06-c55d-437a-941e-008c0921c23d/isActive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZWxpbUBzZWxpbS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImp0aSI6ImNmYTkzNmRiLWQxYTYtNDJmNC04ZTIzLTZiNmE5YzU1NDViYSIsImV4cCI6MTczNDA3MzE3NSwiaXNzIjoiSnd0QXV0aEFwcCIsImF1ZCI6Ikp3dEF1dGhBcHBVc2VyIn0.FDKjUwilCkGU1W2JSYMjp0HMjtmfmHV3vqqIfFWhD9o
Content-Type: application/json

{
  "IsActive": false
}
